//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.FG.FFL.WebParts.FlashReportOffForm {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class FlashReportOffForm {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl FRID_spn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl header_spn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlAnchor IR_link;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl IR_IReceivingDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl FlashIssueDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect Unit_Section_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden Unit_Section_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl DateOfIncident_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl TimeOfIncident_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTable grdAttachments;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.FileUpload fileUploadControl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnFilesNames;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea Description1_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea ActionTaken_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText IncidentScore_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ActionRequired_Unit_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect ResponsibleSection_Unit_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ResponsibleSection_Unit_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect ResponsibleDepartmentt_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ResponsibleDepartmentt_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl TargetDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker ApprovingAuthority_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField ApprovingAuthority_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker TeamLead_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField TeamLead_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker TeamMembers_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField TeamMembers_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea Description2_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnIRID;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSaveAsDraft;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(FlashReportOffForm target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlFRID_spn() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            this.FRID_spn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "col-lg-12");
            @__ctrl.ID = "FRID_spn";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlheader_spn() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            this.header_spn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "col-lg-12");
            @__ctrl.ID = "header_spn";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlAnchor @__BuildControlIR_link() {
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlAnchor();
            this.IR_link = @__ctrl;
            @__ctrl.HRef = "";
            @__ctrl.ID = "IR_link";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("View IR-1"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlIR_IReceivingDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.IR_IReceivingDate_dtc = @__ctrl;
            @__ctrl.ID = "IR_IReceivingDate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlFlashIssueDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.FlashIssueDate_dtc = @__ctrl;
            @__ctrl.ID = "FlashIssueDate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlUnit_Section_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.Unit_Section_ddl = @__ctrl;
            @__ctrl.ID = "Unit_Section_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "select2 col-lg-12 form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlUnit_Section_hdn() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.Unit_Section_hdn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "Unit_Section_hdn";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDateOfIncident_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.DateOfIncident_dtc = @__ctrl;
            @__ctrl.ID = "DateOfIncident_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlTimeOfIncident_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.TimeOfIncident_dtc = @__ctrl;
            @__ctrl.ID = "TimeOfIncident_dtc";
            @__ctrl.TimeOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTable @__BuildControlgrdAttachments() {
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTable();
            this.grdAttachments = @__ctrl;
            @__ctrl.ID = "grdAttachments";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlfileUploadControl() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            this.fileUploadControl = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "fileUploadControl";
            @__ctrl.AllowMultiple = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnFilesNames() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnFilesNames = @__ctrl;
            @__ctrl.ID = "hdnFilesNames";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlDescription1_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.Description1_ta = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "Description1_ta";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlActionTaken_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.ActionTaken_ta = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "ActionTaken_ta";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlIncidentScore_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.IncidentScore_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "IncidentScore_tf";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "IR-5 Filled";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlActionRequired_Unit_ddl() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ActionRequired_Unit_ddl = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ActionRequired_Unit_ddl";
            @__ctrl.CssClass = "form-control";
            @__ctrl.AutoPostBack = false;
            this.@__BuildControl__control2(@__ctrl.Items);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlResponsibleSection_Unit_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.ResponsibleSection_Unit_ddl = @__ctrl;
            @__ctrl.ID = "ResponsibleSection_Unit_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "select2 col-lg-12 form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlResponsibleSection_Unit_hdn() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.ResponsibleSection_Unit_hdn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "ResponsibleSection_Unit_hdn";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlResponsibleDepartmentt_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.ResponsibleDepartmentt_ddl = @__ctrl;
            @__ctrl.ID = "ResponsibleDepartmentt_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "select2 col-lg-12 form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlResponsibleDepartmentt_hdn() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.ResponsibleDepartmentt_hdn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "ResponsibleDepartmentt_hdn";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlTargetDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.TargetDate_dtc = @__ctrl;
            @__ctrl.ID = "TargetDate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlApprovingAuthority_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.ApprovingAuthority_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ApprovingAuthority_PeopleEditor";
            @__ctrl.Rows = 1;
            @__ctrl.VisibleSuggestions = 3;
            @__ctrl.AllowMultipleEntities = true;
            @__ctrl.PrincipalAccountType = "User";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlApprovingAuthority_hdn() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.ApprovingAuthority_hdn = @__ctrl;
            @__ctrl.ID = "ApprovingAuthority_hdn";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlTeamLead_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.TeamLead_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "TeamLead_PeopleEditor";
            @__ctrl.Rows = 1;
            @__ctrl.VisibleSuggestions = 3;
            @__ctrl.AllowMultipleEntities = false;
            @__ctrl.PrincipalAccountType = "User";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlTeamLead_hdn() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.TeamLead_hdn = @__ctrl;
            @__ctrl.ID = "TeamLead_hdn";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlTeamMembers_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.TeamMembers_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "TeamMembers_PeopleEditor";
            @__ctrl.Rows = 1;
            @__ctrl.VisibleSuggestions = 3;
            @__ctrl.AllowMultipleEntities = true;
            @__ctrl.PrincipalAccountType = "User";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlTeamMembers_hdn() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.TeamMembers_hdn = @__ctrl;
            @__ctrl.ID = "TeamMembers_hdn";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlDescription2_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.Description2_ta = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.Rows = 6;
            @__ctrl.ID = "Description2_ta";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnIRID() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnIRID = @__ctrl;
            @__ctrl.ID = "hdnIRID";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSaveAsDraft() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSaveAsDraft = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSaveAsDraft";
            @__ctrl.Text = "Save As Draft";
            @__ctrl.CssClass = "btnSaveAsDraft";
            @__ctrl.Click -= new System.EventHandler(this.btnSaveAsDraft_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSaveAsDraft_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSave";
            @__ctrl.Text = "Submit";
            @__ctrl.OnClientClick = "return Save_Click();";
            @__ctrl.CssClass = "btnSave";
            @__ctrl.Click -= new System.EventHandler(this.btnSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel";
            @__ctrl.Text = "Cancel";
            @__ctrl.CssClass = "btnCancel";
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SL.FG.FFL.WebParts.FlashReportOffForm.FlashReportOffForm @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"




<link href=""/_layouts/15/SL.FG.FFL/CSS/FGStyle.css"" rel=""stylesheet"" />

<div class=""container"">
    <div class=""row"">
        <div class=""col-sm-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    Flash Report
                </div>
                <div class=""panel-body"">
                    <div class=""form-group row"">
                        <div class=""col-lg-4"">
                            <label>Flash Report ID:"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlFRID_spn();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</label>\r\n\r\n\r\n                        </div>\r\n                        <div class=" +
                        "\"col-lg-6\">\r\n                            <label>"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlheader_spn();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</label>\r\n                        </div>\r\n                        <div class=\"col" +
                        "-lg-2\">\r\n                            "));
            global::System.Web.UI.HtmlControls.HtmlAnchor @__ctrl3;
            @__ctrl3 = this.@__BuildControlIR_link();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </div>
                    </div>
                    
                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <label>IR-I receiving Date</label>
                                <div class=""form-group"">
                                    "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl4;
            @__ctrl4 = this.@__BuildControlIR_IReceivingDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    <label id=""IR_IReceivingDate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>

                            </div>
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Flash issue Date</label>
                                    <div class=""form-group"">
                                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl5;
            @__ctrl5 = this.@__BuildControlFlashIssueDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                        <label id=""FlashIssueDate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <label>Unit/Section</label>
                                "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl6;
            @__ctrl6 = this.@__BuildControlUnit_Section_ddl();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl7;
            @__ctrl7 = this.@__BuildControlUnit_Section_hdn();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""Unit_Section_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                            <div class=""col-lg-6"">
                                <label>Date of Incident</label>
                                <div class=""form-group"">
                                    "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl8;
            @__ctrl8 = this.@__BuildControlDateOfIncident_dtc();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    <label id=""DateOfIncident_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>

                            </div>
                        </div>
                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <label>Time of Incident</label>
                                <div class=""form-group"">
                                    "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl9;
            @__ctrl9 = this.@__BuildControlTimeOfIncident_dtc();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    <label id=""TimeOfIncident_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>

                            </div>
                            <div class=""col-lg-6"">
                                <label>Attachment</label>
                                <div>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl10;
            @__ctrl10 = this.@__BuildControlgrdAttachments();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n                                "));
            global::System.Web.UI.WebControls.FileUpload @__ctrl11;
            @__ctrl11 = this.@__BuildControlfileUploadControl();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl12;
            @__ctrl12 = this.@__BuildControlhdnFilesNames();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        </div>\r\n           " +
                        "             <div class=\"form-group\">\r\n                            <label>Descri" +
                        "ption</label>\r\n                            "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl13;
            @__ctrl13 = this.@__BuildControlDescription1_ta();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            <label id=""Description1_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                        </div>
                        <div class=""form-group"">
                            <label>Action taken</label>
                            "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl14;
            @__ctrl14 = this.@__BuildControlActionTaken_ta();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            <label id=""ActionTaken_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                        </div>


                        <div class=""panel panel-success"">
                            <div class=""panel-heading"">
                                Risk based classification of process incident
                            </div>
                            <div class=""panel-body"">
                               
                                    <div class=""form-group row"">
                                        <div class=""col-lg-6"">
                                            <label>Incident Score</label>
                                            "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl15;
            @__ctrl15 = this.@__BuildControlIncidentScore_tf();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                            <label id=""IncidentScore_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                        </div>
                                        <div class=""col-lg-6"">
                                            <label>Action required</label>
                                            "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl16;
            @__ctrl16 = this.@__BuildControlActionRequired_Unit_ddl();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                            <label id=""ActionRequired_Unit_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <div class=""col-lg-6"">
                                            <label>Responsible Section/Unit</label>

                                            "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl17;
            @__ctrl17 = this.@__BuildControlResponsibleSection_Unit_ddl();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                            "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl18;
            @__ctrl18 = this.@__BuildControlResponsibleSection_Unit_hdn();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                            <label id=""ResponsibleSection_Unit_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                        </div>
                                        <div class=""col-lg-6"">
                                            <label>Responsible Department</label>

                                            "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl19;
            @__ctrl19 = this.@__BuildControlResponsibleDepartmentt_ddl();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                            "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl20;
            @__ctrl20 = this.@__BuildControlResponsibleDepartmentt_hdn();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                            <label id=""ResponsibleDepartmentt_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <div class=""col-lg-6"">
                                            <label>Target Date</label>
                                            <div class=""form-group"">
                                                "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl21;
            @__ctrl21 = this.@__BuildControlTargetDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl21);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                <label id=""TargetDate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                            </div>

                                        </div>
                                        <div class=""col-lg-6"">
                                            <div class=""form-group"">
                                                <label>Approving Authority</label>
                                                "));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl22;
            @__ctrl22 = this.@__BuildControlApprovingAuthority_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl22);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl23;
            @__ctrl23 = this.@__BuildControlApprovingAuthority_hdn();
            @__parser.AddParsedSubObject(@__ctrl23);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                <label id=""ApprovingAuthority_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class=""form-group row"">
                                        <div class=""col-lg-6"">
                                            <label>Team Lead</label>
                                            "));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl24;
            @__ctrl24 = this.@__BuildControlTeamLead_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl24);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                            "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl25;
            @__ctrl25 = this.@__BuildControlTeamLead_hdn();
            @__parser.AddParsedSubObject(@__ctrl25);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                            <label id=""TeamLead_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                        </div>
                                        <div class=""col-lg-6"">
                                            <label>Team Members</label>
                                            
                                            "));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl26;
            @__ctrl26 = this.@__BuildControlTeamMembers_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl26);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                            "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl27;
            @__ctrl27 = this.@__BuildControlTeamMembers_hdn();
            @__parser.AddParsedSubObject(@__ctrl27);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                            <label id=""TeamMembers_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                        </div>

                                    </div>
                                    <div class=""form-group row"">
                                        <div class=""col-lg-6"">
                                        </div>
                                        <div class=""col-lg-6"">
                                            <label>
                                                Remarks
                                            </label>
                                            <div class=""form-group"">
                                                "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl28;
            @__ctrl28 = this.@__BuildControlDescription2_ta();
            @__parser.AddParsedSubObject(@__ctrl28);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                <label id=""Description2_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                            </div>
                                        </div>
                                    </div>
                               
                            </div>
                        </div>

                        "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl29;
            @__ctrl29 = this.@__BuildControlhdnIRID();
            @__parser.AddParsedSubObject(@__ctrl29);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                        <div class=\"form-group pull-right\">\r\n                " +
                        "            "));
            global::System.Web.UI.WebControls.Button @__ctrl30;
            @__ctrl30 = this.@__BuildControlbtnSaveAsDraft();
            @__parser.AddParsedSubObject(@__ctrl30);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.Button @__ctrl31;
            @__ctrl31 = this.@__BuildControlbtnSave();
            @__parser.AddParsedSubObject(@__ctrl31);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            global::System.Web.UI.WebControls.Button @__ctrl32;
            @__ctrl32 = this.@__BuildControlbtnCancel();
            @__parser.AddParsedSubObject(@__ctrl32);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

<script src=""/_layouts/15/SL.FG.FFL/Scripts/jQuery.js""></script>

<script src=""/_layouts/15/SL.FG.FFL/Scripts/Validation/FlashReportOff.js""></script>

<script type=""text/javascript"">





    $('[id$=Unit_Section_ddl]').on('change', function () {

        $(""[id$=Unit_Section_hdn]"").val($(this).val());



    })

    $('[id$=ResponsibleSection_Unit_ddl]').on('change', function () {

        $(""[id$=ResponsibleSection_Unit_hdn]"").val($(this).val());


    })


    $('[id$=ResponsibleDepartmentt_ddl]').on('change', function () {

        $(""[id$=ResponsibleDepartmentt_hdn]"").val($(this).val());

    })


</script>

<script>

    $(document).ready(function () {

        $('[id$=IR_IReceivingDate_dtcDate] ').attr(""disabled"", ""disabled"");
    });

</script>
"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
