//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.FG.FFL.WebParts.IR01OnForm {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class IR01OnForm {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect IncidentCategory_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea IncidentCategory_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden IncidentCategory_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect InjuryCategory_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea InjuryCategory_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden InjuryCategory_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect EmployeeType_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect ConsentTaken_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MOConsent_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl Date_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker MOName_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText MOName_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MOName_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MORemarks_str;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MORemarks_ldl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea MORemarks_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTable grdAttachments;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.FileUpload fileUploadControl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnFilesNames;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MOFields_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl DateOfIncident_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl TimeOfIncident_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect Unit_Area_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden Unit_Area_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText IncidentScore_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker SubmittedBy_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SubmittedBy_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText SubmittedBy_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl SubmissionDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText Title_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea Description_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea ActionTaken_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox ReportRequired_cb;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox TeamRequired_cb;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSaveAsDraft;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnMOSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnHSESave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(IR01OnForm target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlIncidentCategory_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.IncidentCategory_ddl = @__ctrl;
            @__ctrl.ID = "IncidentCategory_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "select2 col-lg-12 form-control");
            @__ctrl.Multiple = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlIncidentCategory_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.IncidentCategory_ta = @__ctrl;
            @__ctrl.ID = "IncidentCategory_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlIncidentCategory_hdn() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.IncidentCategory_hdn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "IncidentCategory_hdn";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlInjuryCategory_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.InjuryCategory_ddl = @__ctrl;
            @__ctrl.ID = "InjuryCategory_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "select2 col-lg-12 form-control");
            @__ctrl.Multiple = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlInjuryCategory_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.InjuryCategory_ta = @__ctrl;
            @__ctrl.ID = "InjuryCategory_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlInjuryCategory_hdn() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.InjuryCategory_hdn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "InjuryCategory_hdn";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control2() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "Please Select";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "FFL";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control4() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Contractor";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlEmployeeType_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.EmployeeType_ddl = @__ctrl;
            @__ctrl.ID = "EmployeeType_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control3();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control4();
            @__parser.AddParsedSubObject(@__ctrl3);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control5() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "Please Select";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control6() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Yes";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control7() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "No";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control8() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "N/A";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlConsentTaken_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.ConsentTaken_ddl = @__ctrl;
            @__ctrl.ID = "ConsentTaken_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control5();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control6();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control7();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control8();
            @__parser.AddParsedSubObject(@__ctrl4);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlMOConsent_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.MOConsent_div = @__ctrl;
            @__ctrl.ID = "MOConsent_div";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    <label>Consent Taken<span style=\"color: red" +
                        "\">&nbsp;*</span></label>\r\n                                    "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl1;
            @__ctrl1 = this.@__BuildControlConsentTaken_ddl();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    <label id=\"ConsentTaken_msg\" hidden style=\"" +
                        "color: red\">You can\'t leave this empty.</label>\r\n                               " +
                        " "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.Date_dtc = @__ctrl;
            @__ctrl.ID = "Date_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            @__ctrl.Load -= new System.EventHandler(this.Date_dtc_DateChanged);
            @__ctrl.Load += new System.EventHandler(this.Date_dtc_DateChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlMOName_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.MOName_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "MOName_PeopleEditor";
            @__ctrl.Rows = 1;
            @__ctrl.VisibleSuggestions = 3;
            @__ctrl.AllowMultipleEntities = false;
            @__ctrl.PrincipalAccountType = "User";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlMOName_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.MOName_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "MOName_tf";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlMOName_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.MOName_div = @__ctrl;
            @__ctrl.ID = "MOName_div";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        <div class=""form-group"">
                            <div class=""row"">
                                <div class=""col-lg-6"">
                                    <label>Date of Consent Taken<span style=""color: red"">&nbsp;*</span></label>

                                    <div class=""form-group"">
                                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                    <label id=""Date_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                                <div class=""col-lg-6"">



                                    <label>MO Name<span style=""color: red"">&nbsp;*</span></label>
                                    "));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl2;
            @__ctrl2 = this.@__BuildControlMOName_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n                                <label " +
                        "id=\"MOName_PeopleEditor_msg\" hidden style=\"color: red\">You can\'t leave this empt" +
                        "y.</label>\r\n\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl3;
            @__ctrl3 = this.@__BuildControlMOName_tf();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        </div>\r\n           " +
                        "         "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlMORemarks_str() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("span");
            this.MORemarks_str = @__ctrl;
            @__ctrl.ID = "MORemarks_str";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "color: red");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("&nbsp;*"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlMORemarks_ldl() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("label");
            this.MORemarks_ldl = @__ctrl;
            @__ctrl.ID = "MORemarks_ldl";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("MO Remarks"));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlMORemarks_str();
            @__parser.AddParsedSubObject(@__ctrl1);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlMORemarks_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.MORemarks_ta = @__ctrl;
            @__ctrl.ID = "MORemarks_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTable @__BuildControlgrdAttachments() {
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTable();
            this.grdAttachments = @__ctrl;
            @__ctrl.ID = "grdAttachments";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlfileUploadControl() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            this.fileUploadControl = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "fileUploadControl";
            @__ctrl.AllowMultiple = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnFilesNames() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnFilesNames = @__ctrl;
            @__ctrl.ID = "hdnFilesNames";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlMOFields_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.MOFields_div = @__ctrl;
            @__ctrl.ID = "MOFields_div";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            <div class=\"col-lg-6\">\r\n\r\n                         " +
                        "       "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlMORemarks_ldl();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl2;
            @__ctrl2 = this.@__BuildControlMORemarks_ta();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""MORemarks_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>

                            <div class=""col-lg-6"">
                                <label>Attachment</label>
                                <div>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl3;
            @__ctrl3 = this.@__BuildControlgrdAttachments();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n                                "));
            global::System.Web.UI.WebControls.FileUpload @__ctrl4;
            @__ctrl4 = this.@__BuildControlfileUploadControl();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl5;
            @__ctrl5 = this.@__BuildControlhdnFilesNames();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDateOfIncident_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.DateOfIncident_dtc = @__ctrl;
            @__ctrl.ID = "DateOfIncident_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            @__ctrl.Load -= new System.EventHandler(this.DateOfIncident_dtc_DateChanged);
            @__ctrl.Load += new System.EventHandler(this.DateOfIncident_dtc_DateChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlTimeOfIncident_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.TimeOfIncident_dtc = @__ctrl;
            @__ctrl.ID = "TimeOfIncident_dtc";
            @__ctrl.TimeOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control9() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "Please Select";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlUnit_Area_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.Unit_Area_ddl = @__ctrl;
            @__ctrl.ID = "Unit_Area_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "select2 col-lg-12 form-control");
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control9();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlUnit_Area_hdn() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.Unit_Area_hdn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "Unit_Area_hdn";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlIncidentScore_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.IncidentScore_tf = @__ctrl;
            @__ctrl.ID = "IncidentScore_tf";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlSubmittedBy_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.SubmittedBy_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "SubmittedBy_PeopleEditor";
            @__ctrl.Rows = 1;
            @__ctrl.VisibleSuggestions = 3;
            @__ctrl.AllowMultipleEntities = false;
            @__ctrl.PrincipalAccountType = "User";
            @__ctrl.Enabled = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlSubmittedBy_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.SubmittedBy_div = @__ctrl;
            @__ctrl.ID = "SubmittedBy_div";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    "));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl1;
            @__ctrl1 = this.@__BuildControlSubmittedBy_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlSubmittedBy_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.SubmittedBy_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "SubmittedBy_tf";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlSubmissionDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.SubmissionDate_dtc = @__ctrl;
            @__ctrl.ID = "SubmissionDate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            @__ctrl.Load -= new System.EventHandler(this.SubmissionDate_dtc_DateChanged);
            @__ctrl.Load += new System.EventHandler(this.SubmissionDate_dtc_DateChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlTitle_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.Title_tf = @__ctrl;
            @__ctrl.ID = "Title_tf";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlDescription_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.Description_ta = @__ctrl;
            @__ctrl.ID = "Description_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlActionTaken_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.ActionTaken_ta = @__ctrl;
            @__ctrl.ID = "ActionTaken_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputCheckBox @__BuildControlReportRequired_cb() {
            global::System.Web.UI.HtmlControls.HtmlInputCheckBox @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputCheckBox();
            this.ReportRequired_cb = @__ctrl;
            @__ctrl.ID = "ReportRequired_cb";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "checkbox");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputCheckBox @__BuildControlTeamRequired_cb() {
            global::System.Web.UI.HtmlControls.HtmlInputCheckBox @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputCheckBox();
            this.TeamRequired_cb = @__ctrl;
            @__ctrl.ID = "TeamRequired_cb";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "checkbox");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSaveAsDraft() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSaveAsDraft = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSaveAsDraft";
            @__ctrl.Text = "Save As Draft";
            @__ctrl.CssClass = "btnSaveAsDraft";
            @__ctrl.Click -= new System.EventHandler(this.btnSaveAsDraft_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSaveAsDraft_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSave";
            @__ctrl.Text = "Submit";
            @__ctrl.OnClientClick = "return Save_Click();";
            @__ctrl.CssClass = "btnSave";
            @__ctrl.Click -= new System.EventHandler(this.btnSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnMOSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnMOSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnMOSave";
            @__ctrl.Text = "Submit";
            @__ctrl.Visible = false;
            @__ctrl.OnClientClick = "return MOSave_Click();";
            @__ctrl.CssClass = "btnSave";
            @__ctrl.Click -= new System.EventHandler(this.btnMOSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnMOSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnHSESave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnHSESave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnHSESave";
            @__ctrl.Text = "Submit";
            @__ctrl.Visible = false;
            @__ctrl.OnClientClick = "return Save_Click();";
            @__ctrl.CssClass = "btnSave";
            @__ctrl.Click -= new System.EventHandler(this.btnHSE_Click);
            @__ctrl.Click += new System.EventHandler(this.btnHSE_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel";
            @__ctrl.Text = "Cancel";
            @__ctrl.CssClass = "btnCancel";
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SL.FG.FFL.WebParts.IR01OnForm.IR01OnForm @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"


<link href=""/_layouts/15/SL.FG.FFL/CSS/FGStyle.css"" rel=""stylesheet"" />

<div class=""container"">
    <div class=""row"">
        <div class=""col-sm-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    IR-I
                </div>
                <div class=""panel-body"">

                    <div class=""form-group"">
                        <div class=""row"">
                            <div class=""col-lg-6"">
                                <label>Incident Category<span style=""color: red"">&nbsp;*</span></label>
                                <br />
                                "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl1;
            @__ctrl1 = this.@__BuildControlIncidentCategory_ddl();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl2;
            @__ctrl2 = this.@__BuildControlIncidentCategory_ta();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                <label id=\"IncidentCategory_msg\" hidden style=\"" +
                        "color: red\">You can\'t leave this empty.</label>\r\n                               " +
                        " "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl3;
            @__ctrl3 = this.@__BuildControlIncidentCategory_hdn();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                            <div class=""col-lg-6"">
                                <label>Injury Category<span style=""color: red"">&nbsp;*</span></label>
                                <br />
                                "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl4;
            @__ctrl4 = this.@__BuildControlInjuryCategory_ddl();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl5;
            @__ctrl5 = this.@__BuildControlInjuryCategory_ta();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                <label id=\"InjuryCategory_msg\" hidden style=\"co" +
                        "lor: red\">You can\'t leave this empty.</label>\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl6;
            @__ctrl6 = this.@__BuildControlInjuryCategory_hdn();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                    <div class=""form-group"">
                        <div class=""row"">
                            <div class=""col-lg-6"">
                                <label>Employee Type<span style=""color: red"">&nbsp;*</span></label>
                                "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl7;
            @__ctrl7 = this.@__BuildControlEmployeeType_ddl();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                <label id=\"EmployeeType_msg\" hidden style=\"colo" +
                        "r: red\">You can\'t leave this empty.</label>\r\n                            </div>\r" +
                        "\n                            <div class=\"col-lg-6\">\r\n                           " +
                        "     "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl8;
            @__ctrl8 = this.@__BuildControlMOConsent_div();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        </div>\r\n           " +
                        "         </div>\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl9;
            @__ctrl9 = this.@__BuildControlMOName_div();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n                <div class=\"form-group\">\r\n             " +
                        "       <div class=\"row\">\r\n                        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl10;
            @__ctrl10 = this.@__BuildControlMOFields_div();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        
                    </div>
                </div>

                <div class=""panel panel-success"">
                    <div class=""panel-heading"">
                        Incident Details
                    </div>
                    <div class=""panel-body"">
                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <label>Date of Incident<span style=""color: red"">&nbsp;*</span></label>
                                <div class=""form-group"">
                                    "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl11;
            @__ctrl11 = this.@__BuildControlDateOfIncident_dtc();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                                <label id=""DateOfIncident_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Time of Incident<span style=""color: red"">&nbsp;*</span></label>
                                    <div class=""form-group"">
                                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl12;
            @__ctrl12 = this.@__BuildControlTimeOfIncident_dtc();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                    <label id=""TimeOfIncident_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                            </div>
                        </div>
                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <label>Unit/Area<span style=""color: red"">&nbsp;*</span></label>
                                <br />
                                "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl13;
            @__ctrl13 = this.@__BuildControlUnit_Area_ddl();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                <label id=\"Unit_Area_msg\" hidden style=\"color: " +
                        "red\">You can\'t leave this empty.</label>\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl14;
            @__ctrl14 = this.@__BuildControlUnit_Area_hdn();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                            <div class=\"col" +
                        "-lg-6\">\r\n                                <label>Incident Score<span style=\"color" +
                        ": red\">&nbsp;*</span></label>\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl15;
            @__ctrl15 = this.@__BuildControlIncidentScore_tf();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""IncidentScore_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                        </div>
                        <div class=""form-group row"">
                            <div class=""col-lg-6 table-responsive"">

                                <label>Submitted by<span style=""color: red"">&nbsp;*</span></label>
                                "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl16;
            @__ctrl16 = this.@__BuildControlSubmittedBy_div();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl17;
            @__ctrl17 = this.@__BuildControlSubmittedBy_tf();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""SubmittedBy_PeopleEditor_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                            <div class=""col-lg-6"">
                                <label>Submission Date<span style=""color: red"">&nbsp;*</span></label>
                                <div class=""form-group"">
                                    "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl18;
            @__ctrl18 = this.@__BuildControlSubmissionDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                                <label id=""SubmissionDate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                        </div>

                        <div class=""form-group row"">
                            <div class=""col-lg-12"">
                                <label>Title<span style=""color: red"">&nbsp;*</span></label>
                                "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl19;
            @__ctrl19 = this.@__BuildControlTitle_tf();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""Title_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                        </div>
                        <div class=""form-group row"">
                            <div class=""col-lg-12"">
                                <label>Description<span style=""color: red"">&nbsp;*</span></label>
                                "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl20;
            @__ctrl20 = this.@__BuildControlDescription_ta();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""Description_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                        </div>
                        <div class=""form-group row"">
                            <div class=""col-lg-12"">
                                <label>Action taken<span style=""color: red"">&nbsp;*</span></label>
                                "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl21;
            @__ctrl21 = this.@__BuildControlActionTaken_ta();
            @__parser.AddParsedSubObject(@__ctrl21);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""ActionTaken_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                        </div>
                        <div class=""form-group row"">

                            <div class=""col-lg-6"">
                                <div class=""form-inline"">
                                    <label>Is detailed report required on IR-03 Form? &nbsp;&nbsp;</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputCheckBox @__ctrl22;
            @__ctrl22 = this.@__BuildControlReportRequired_cb();
            @__parser.AddParsedSubObject(@__ctrl22);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>
                            <div class=""col-lg-6"">
                                <div class=""form-inline"">
                                    <label>If so, is investigation team required? &nbsp;&nbsp;</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputCheckBox @__ctrl23;
            @__ctrl23 = this.@__BuildControlTeamRequired_cb();
            @__parser.AddParsedSubObject(@__ctrl23);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class=""form-group pull-right"">
            "));
            global::System.Web.UI.WebControls.Button @__ctrl24;
            @__ctrl24 = this.@__BuildControlbtnSaveAsDraft();
            @__parser.AddParsedSubObject(@__ctrl24);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl25;
            @__ctrl25 = this.@__BuildControlbtnSave();
            @__parser.AddParsedSubObject(@__ctrl25);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl26;
            @__ctrl26 = this.@__BuildControlbtnMOSave();
            @__parser.AddParsedSubObject(@__ctrl26);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl27;
            @__ctrl27 = this.@__BuildControlbtnHSESave();
            @__parser.AddParsedSubObject(@__ctrl27);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl28;
            @__ctrl28 = this.@__BuildControlbtnCancel();
            @__parser.AddParsedSubObject(@__ctrl28);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n\r\n    </div>\r\n</div>\r\n\r\n\r\n<script src=\"/_layouts/15/SL.FG.FFL/S" +
                        "cripts/jQuery.js\"></script>\r\n\r\n<script src=\"/_layouts/15/SL.FG.FFL/Scripts/Valid" +
                        "ation/IR01On.js\"></script>\r\n\r\n\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    $(docum" +
                        "ent).ready(function () {\r\n\r\n        $(\"[id$=IncidentCategory_ddl]\").each(functio" +
                        "n () {\r\n\r\n            if ($(\"[id$=IncidentCategory_ddl] option:selected\").val() " +
                        "!= \"null\" && $(\"[id$=IncidentCategory_ddl] option:selected\").val() != \"undefined" +
                        "\") {\r\n\r\n                var value = $(this).val();\r\n                if (value !=" +
                        " \"\" && value != \"undefined\") {\r\n                    if (value.indexOf(\"Injury\") " +
                        ">= 0) {\r\n\r\n                        $(\"[id$=MOConsent_div]\").attr(\"style\", \"displ" +
                        "ay:normal\");\r\n\r\n                        $(\"[id$=ConsentTaken_ddl]\").each(functio" +
                        "n () {\r\n\r\n                            var value = $(this).val();\r\n\r\n            " +
                        "                if (value.indexOf(\"Yes\") >= 0) {\r\n\r\n                            " +
                        "    $(\"[id$=MOName_div]\").attr(\"style\", \"display:normal\");\r\n                    " +
                        "        }\r\n                        });\r\n                    }\r\n                }" +
                        "\r\n            }\r\n        });\r\n\r\n    });\r\n\r\n    $(\'[id$=IncidentCategory_ddl]\').o" +
                        "n(\'change\', function () {\r\n\r\n        $(\"[id$=IncidentCategory_ddl]\").each(functi" +
                        "on () {\r\n\r\n            $(\"[id$=IncidentCategory_hdn]\").val($(this).val());\r\n\r\n  " +
                        "          var value = $(this).val();\r\n\r\n            if (value.indexOf(\"Injury\") " +
                        ">= 0) {\r\n\r\n                $(\"[id$=MOConsent_div]\").show(\"fast\");\r\n\r\n           " +
                        "     $(\"[id$=ConsentTaken_ddl]\").each(function () {\r\n\r\n                    var v" +
                        "alue = $(this).val();\r\n\r\n                    if (value.indexOf(\"Yes\") >= 0) {\r\n\r" +
                        "\n                        $(\"[id$=MOName_div]\").show(\"fast\");\r\n                  " +
                        "  }\r\n                    else {\r\n                        $(\"[id$=MOName_div]\").h" +
                        "ide(\"fast\");\r\n\r\n                    }\r\n\r\n                });\r\n\r\n            }\r\n " +
                        "           else {\r\n                $(\"[id$=MOConsent_div]\").hide(\"fast\");\r\n     " +
                        "           $(\"[id$=MOName_div]\").hide(\"fast\");\r\n            }\r\n\r\n        });\r\n\r\n" +
                        "    })\r\n\r\n    $(\'[id$=ConsentTaken_ddl]\').on(\'change\', function () {\r\n\r\n        " +
                        "$(\"[id$=ConsentTaken_ddl]\").each(function () {\r\n\r\n            var value = $(this" +
                        ").val();\r\n\r\n            if (value.indexOf(\"Yes\") >= 0) {\r\n\r\n                $(\"[" +
                        "id$=MOName_div]\").show(\"fast\");\r\n            }\r\n            else {\r\n            " +
                        "    $(\"[id$=MOName_div]\").hide(\"fast\");\r\n\r\n            }\r\n\r\n        });\r\n\r\n    }" +
                        ")\r\n\r\n\r\n\r\n\r\n    $(\'[id$=InjuryCategory_ddl]\').on(\'change\', function () {\r\n\r\n     " +
                        "   $(\"[id$=InjuryCategory_ddl]\").each(function () {\r\n\r\n            $(\"[id$=Injur" +
                        "yCategory_hdn]\").val($(this).val());\r\n\r\n        });\r\n\r\n\r\n    })\r\n\r\n\r\n    $(\'[id$" +
                        "=Unit_Area_ddl]\').on(\'change\', function () {\r\n\r\n        $(\"[id$=Unit_Area_hdn]\")" +
                        ".val($(this).val());\r\n\r\n    })\r\n\r\n\r\n</script>\r\n\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
