//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.FG.FFL.WebParts.WorkQueue {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class WorkQueue {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl message_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdMSAScheduled;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdMSATask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdMSARecommendationTask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdIR01DITasks;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdIR03DITasks;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdIRRecommendationsOnJob;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdIIROffJobTask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdFROffJobTask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdIR05OffJobTask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdIR5OffJobRecomendationTask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdWaiverOnJobTask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdWaiverOffJobTask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdIR01Task;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdFlashReportTask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(WorkQueue target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlmessage_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.message_div = @__ctrl;
            @__ctrl.ID = "message_div";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "messageDiv");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdMSAScheduled() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdMSAScheduled = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdMSAScheduled";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdMSATask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdMSATask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdMSATask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdMSARecommendationTask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdMSARecommendationTask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdMSARecommendationTask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdIR01DITasks() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdIR01DITasks = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdIR01DITasks";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdIR03DITasks() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdIR03DITasks = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdIR03DITasks";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdIRRecommendationsOnJob() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdIRRecommendationsOnJob = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdIRRecommendationsOnJob";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdIIROffJobTask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdIIROffJobTask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdIIROffJobTask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdFROffJobTask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdFROffJobTask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdFROffJobTask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdIR05OffJobTask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdIR05OffJobTask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdIR05OffJobTask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdIR5OffJobRecomendationTask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdIR5OffJobRecomendationTask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdIR5OffJobRecomendationTask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdWaiverOnJobTask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdWaiverOnJobTask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdWaiverOnJobTask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdWaiverOffJobTask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdWaiverOffJobTask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdWaiverOffJobTask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdIR01Task() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdIR01Task = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdIR01Task";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdFlashReportTask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdFlashReportTask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdFlashReportTask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SL.FG.FFL.WebParts.WorkQueue.WorkQueue @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<link href=\"/_layouts/15/SL.FG.FFL/CSS/FGStyle.css\" rel=\"stylesheet\" />\r\n\r\n" +
                        "<div class=\"container\">\r\n    <div class=\"row\">\r\n        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlmessage_div();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

        <!--Rizwan -->
        <!--Start -->
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>MSA Schedule</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse3"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse3"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput3"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl2;
            @__ctrl2 = this.@__BuildControlgrdMSAScheduled();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>MSA (Saved as draft)</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse1"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse1"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput1"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl3;
            @__ctrl3 = this.@__BuildControlgrdMSATask();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>MSA Recommendation</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse2"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse2"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput2"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl4;
            @__ctrl4 = this.@__BuildControlgrdMSARecommendationTask();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>IR01 Detailed Investigation</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse12"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse12"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput12"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl5;
            @__ctrl5 = this.@__BuildControlgrdIR01DITasks();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>IR03 Detailed Investigation</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse13"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse13"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput13"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl6;
            @__ctrl6 = this.@__BuildControlgrdIR03DITasks();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>IR Recommendations On Job</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse11"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse11"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput11"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl7;
            @__ctrl7 = this.@__BuildControlgrdIRRecommendationsOnJob();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        </div>\r\n           " +
                        "         </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n   " +
                        "     <!--End WorkQueue -->\r\n\r\n\r\n        <!--Usama -->\r\n        <!--Start -->\r\n  " +
                        "      <div class=\"col-lg-12\">\r\n            <div class=\"panel panel-success\">\r\n  " +
                        "              <div class=\"panel-heading\">\r\n                    <div class=\"row\">" +
                        "\r\n                        <div class=\"col-lg-9\">\r\n                            <h" +
                        "5>IIR 01 Off The Job Task</h5>\r\n                        </div>\r\n                " +
                        "        <div class=\"col-lg-3\">\r\n                            <span class=\"panel-t" +
                        "itle pull-right\"\r\n                                data-toggle=\"collapse\"\r\n      " +
                        "                          data-target=\"#collapse30\">\r\n                          " +
                        "      <i class=\'glyphicon glyphicon-sort\'></i>\r\n                            </sp" +
                        "an>\r\n                        </div>\r\n                    </div>\r\n               " +
                        " </div>\r\n                <div id=\"collapse30\" class=\"panel-collapse collapse\">\r\n" +
                        "                    <div class=\"panel-body\" style=\"height: 200px; overflow-y: sc" +
                        "roll;\">\r\n                        <div class=\"row\">\r\n                            " +
                        "<div style=\"margin: 10px;\">\r\n                                <input type=\"text\" " +
                        "id=\"searchInput30\" placeholder=\"Search...\" class=\"form-control\" />\r\n            " +
                        "                </div>\r\n                        </div>\r\n                        " +
                        "<div class=\"row\">\r\n                            <div class=\"col-lg-12\">\r\n        " +
                        "                        "));
            global::System.Web.UI.WebControls.GridView @__ctrl8;
            @__ctrl8 = this.@__BuildControlgrdIIROffJobTask();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>Flash Report Off The Job Task</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse32"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse32"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput32"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl9;
            @__ctrl9 = this.@__BuildControlgrdFROffJobTask();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>IR05 Off Job Task</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse34"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse34"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput34"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl10;
            @__ctrl10 = this.@__BuildControlgrdIR05OffJobTask();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>IR05 Off Job Recommendation Task</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse36"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse36"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput36"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl11;
            @__ctrl11 = this.@__BuildControlgrdIR5OffJobRecomendationTask();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>On The Job Waiver Task</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse38"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse38"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput38"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl12;
            @__ctrl12 = this.@__BuildControlgrdWaiverOnJobTask();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>Off The Job Waiver Task</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse39"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse39"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput39"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl13;
            @__ctrl13 = this.@__BuildControlgrdWaiverOffJobTask();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>IIR-01 On The Job Task</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse40"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse40"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput40"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl14;
            @__ctrl14 = this.@__BuildControlgrdIR01Task();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>Flash Report On The Job Task</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse42"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse42"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y: scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput42"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl15;
            @__ctrl15 = this.@__BuildControlgrdFlashReportTask();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
         <!--End WorkQueue -->

    </div>
</div>

<script src=""/_layouts/15/SL.FG.FFL/Scripts/jQuery.js""></script>

<script src=""/_layouts/15/SL.FG.FFL/Scripts/WorkQueue/WorkQueue.js""></script>






"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
