//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.FG.FFL.WebParts.WaiverForm {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class WaiverForm {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText SafetyIncidentReportNo_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText RecommendationNo_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect Section_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden Section_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden Hidden1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect Department_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden Department_hdn;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl Date_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl RecommendationCompletionDueDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea DescriptionOfTheRecommendations_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea RecommendationReason_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl NewTargetDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker InitiatedBy_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl InitiatedDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea InitiaterComments_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Initiator_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker UM_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl UMDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea UMComments_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl UM_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker DM_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl DMDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea DMComments_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DM_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker DO_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl DODate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea DOComments_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DO_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnID;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnRecommendationListName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnParentList;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnFRID;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnLink;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnTaskName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSaveAsDraft;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnUMSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnDMSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnDOSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnUMDisapprive;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnDMDisapprive;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnDODisapprive;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl waiver_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl waiverNotAvailable_lb;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(WaiverForm target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlSafetyIncidentReportNo_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.SafetyIncidentReportNo_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            @__ctrl.ID = "SafetyIncidentReportNo_tf";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlRecommendationNo_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.RecommendationNo_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            @__ctrl.ID = "RecommendationNo_tf";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control2() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "Please Select";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlSection_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.Section_ddl = @__ctrl;
            @__ctrl.ID = "Section_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "select2 col-lg-12 form-control");
            @__ctrl.Disabled = true;
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlSection_hdn() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.Section_hdn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "Section_hdn";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlHidden1() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.Hidden1 = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "Hidden1";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Value = "0";
            @__ctrl.Text = "Please Select";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlDepartment_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.Department_ddl = @__ctrl;
            @__ctrl.ID = "Department_ddl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "select2 col-lg-12 form-control");
            @__ctrl.Disabled = true;
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputHidden @__BuildControlDepartment_hdn() {
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputHidden();
            this.Department_hdn = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "Department_hdn";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Enter text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "hidden");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.Date_dtc = @__ctrl;
            @__ctrl.Enabled = false;
            @__ctrl.ID = "Date_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlRecommendationCompletionDueDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.RecommendationCompletionDueDate_dtc = @__ctrl;
            @__ctrl.Enabled = false;
            @__ctrl.ID = "RecommendationCompletionDueDate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.IsRequiredField = true;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlDescriptionOfTheRecommendations_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.DescriptionOfTheRecommendations_ta = @__ctrl;
            @__ctrl.ID = "DescriptionOfTheRecommendations_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlRecommendationReason_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.RecommendationReason_ta = @__ctrl;
            @__ctrl.ID = "RecommendationReason_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlNewTargetDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.NewTargetDate_dtc = @__ctrl;
            @__ctrl.ID = "NewTargetDate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.IsRequiredField = true;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlInitiatedBy_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.InitiatedBy_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "InitiatedBy_PeopleEditor";
            @__ctrl.Rows = 1;
            @__ctrl.VisibleSuggestions = 3;
            @__ctrl.AllowMultipleEntities = false;
            @__ctrl.PrincipalAccountType = "User";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlInitiatedDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.InitiatedDate_dtc = @__ctrl;
            @__ctrl.ID = "InitiatedDate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlInitiaterComments_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.InitiaterComments_ta = @__ctrl;
            @__ctrl.ID = "InitiaterComments_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlInitiator_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.Initiator_div = @__ctrl;
            @__ctrl.ID = "Initiator_div";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        <div class=""form-group"">
                            <div class=""row"">
                                <div class=""col-lg-6"">
                                    <label>Initiated by<span style=""color: red"">&nbsp;*</span></label>
                                    "));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl1;
            @__ctrl1 = this.@__BuildControlInitiatedBy_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""InitiatedBy_PeopleEditor_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                                
                                <div class=""col-lg-6"">
                                    <label>Initiated Date<span style=""color: red"">&nbsp;*</span></label>

                                    <div class=""form-group"">
                                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlInitiatedDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                     <label id=""InitiatedDate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        <div class=""form-group"">
                            <div class=""row"">
                                <div class=""col-lg-12"">
                                    <label>Initiator comments<span style=""color: red"">&nbsp;*</span></label>

                                    "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl3;
            @__ctrl3 = this.@__BuildControlInitiaterComments_ta();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    <label id=""InitiaterComments_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                            </div>
                        </div>
                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlUM_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.UM_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "UM_PeopleEditor";
            @__ctrl.Rows = 1;
            @__ctrl.VisibleSuggestions = 3;
            @__ctrl.AllowMultipleEntities = false;
            @__ctrl.PrincipalAccountType = "User";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlUMDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.UMDate_dtc = @__ctrl;
            @__ctrl.ID = "UMDate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlUMComments_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.UMComments_ta = @__ctrl;
            @__ctrl.ID = "UMComments_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlUM_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.UM_div = @__ctrl;
            @__ctrl.ID = "UM_div";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        <div class=""form-group"">
                            <div class=""row"">
                                <div class=""col-lg-6"">
                                    <label>Reviewed by UM<span style=""color: red"">&nbsp;*</span></label>
                                    "));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl1;
            @__ctrl1 = this.@__BuildControlUM_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""UM_PeopleEditor_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                                
                                <div class=""col-lg-6"">
                                    <label>Date<span style=""color: red"">&nbsp;*</span></label>

                                    <div class=""form-group"">
                                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlUMDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                     <label id=""UMDate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        <div class=""form-group"">
                            <div class=""row"">
                                <div class=""col-lg-12"">
                                    <label>Comments<span style=""color: red"">&nbsp;*</span></label>

                                    "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl3;
            @__ctrl3 = this.@__BuildControlUMComments_ta();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    <label id=""UMComments_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                            </div>
                        </div>
                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlDM_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.DM_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DM_PeopleEditor";
            @__ctrl.Rows = 1;
            @__ctrl.VisibleSuggestions = 3;
            @__ctrl.AllowMultipleEntities = false;
            @__ctrl.PrincipalAccountType = "User";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDMDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.DMDate_dtc = @__ctrl;
            @__ctrl.ID = "DMDate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlDMComments_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.DMComments_ta = @__ctrl;
            @__ctrl.ID = "DMComments_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlDM_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.DM_div = @__ctrl;
            @__ctrl.ID = "DM_div";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        <div class=""form-group"">
                            <div class=""row"">
                                <div class=""col-lg-6"">
                                    <label>Reviewed by DM<span style=""color: red"">&nbsp;*</span></label>
                                    "));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl1;
            @__ctrl1 = this.@__BuildControlDM_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                  <label id=""DM_PeopleEditor_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                              

                                <div class=""col-lg-6"">
                                    <label>Date<span style=""color: red"">&nbsp;*</span></label>

                                    <div class=""form-group"">
                                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlDMDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    <label id=""DMDate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        <div class=""form-group"">
                            <div class=""row"">
                                <div class=""col-lg-12"">
                                    <label>Comments<span style=""color: red"">&nbsp;*</span></label>

                                    "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl3;
            @__ctrl3 = this.@__BuildControlDMComments_ta();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    <label id=""DMComments_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                            </div>
                        </div>
                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__BuildControlDO_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ClientPeoplePicker();
            this.DO_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "DO_PeopleEditor";
            @__ctrl.Rows = 1;
            @__ctrl.VisibleSuggestions = 3;
            @__ctrl.AllowMultipleEntities = false;
            @__ctrl.PrincipalAccountType = "User";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlDODate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.DODate_dtc = @__ctrl;
            @__ctrl.ID = "DODate_dtc";
            @__ctrl.DateOnly = true;
            @__ctrl.CssClassTextBox = "form-control";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlDOComments_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.DOComments_ta = @__ctrl;
            @__ctrl.ID = "DOComments_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlDO_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.DO_div = @__ctrl;
            @__ctrl.ID = "DO_div";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "display: none");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        <div class=""form-group"">
                            <div class=""row"">
                                <div class=""col-lg-6"">
                                    <label>Reviewed by DO<span style=""color: red"">&nbsp;*</span></label>
                                    "));
            global::Microsoft.SharePoint.WebControls.ClientPeoplePicker @__ctrl1;
            @__ctrl1 = this.@__BuildControlDO_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                 <label id=""DO_PeopleEditor_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                               

                                <div class=""col-lg-6"">
                                    <label>Date<span style=""color: red"">&nbsp;*</span></label>

                                    <div class=""form-group"">
                                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlDODate_dtc();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    <label id=""DODate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        <div class=""form-group"">
                            <div class=""row"">
                                <div class=""col-lg-12"">
                                    <label>Comments<span style=""color: red"">&nbsp;*</span></label>

                                    "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl3;
            @__ctrl3 = this.@__BuildControlDOComments_ta();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                     <label id=""DOComments_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                            </div>
                        </div>
                    "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnID() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnID = @__ctrl;
            @__ctrl.ID = "hdnID";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnRecommendationListName() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnRecommendationListName = @__ctrl;
            @__ctrl.ID = "hdnRecommendationListName";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnParentList() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnParentList = @__ctrl;
            @__ctrl.ID = "hdnParentList";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnFRID() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnFRID = @__ctrl;
            @__ctrl.ID = "hdnFRID";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnLink() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnLink = @__ctrl;
            @__ctrl.ID = "hdnLink";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnTaskName() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnTaskName = @__ctrl;
            @__ctrl.ID = "hdnTaskName";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSaveAsDraft() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSaveAsDraft = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSaveAsDraft";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-info");
            @__ctrl.Visible = false;
            @__ctrl.Text = "Save As Draft";
            @__ctrl.CssClass = "btnSaveAsDraft";
            @__ctrl.Click -= new System.EventHandler(this.btnSaveAsDraft_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSaveAsDraft_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSave";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary");
            @__ctrl.Text = "Submit";
            @__ctrl.OnClientClick = "return Save_Click();";
            @__ctrl.CssClass = "btnSave";
            @__ctrl.Click -= new System.EventHandler(this.btnSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-default");
            @__ctrl.Text = "Cancel";
            @__ctrl.CssClass = "btnCancel";
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnUMSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnUMSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnUMSave";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary");
            @__ctrl.Visible = false;
            @__ctrl.Text = "Reviewed And Approved";
            @__ctrl.OnClientClick = "return Save_Click();";
            @__ctrl.CssClass = "btnApprove";
            @__ctrl.Click -= new System.EventHandler(this.btnUMSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnUMSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnDMSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnDMSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnDMSave";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary");
            @__ctrl.Visible = false;
            @__ctrl.Text = "Reviewed And Approved";
            @__ctrl.OnClientClick = "return Save_Click();";
            @__ctrl.CssClass = "btnApprove";
            @__ctrl.Click -= new System.EventHandler(this.btnDMSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnDMSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnDOSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnDOSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnDOSave";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary");
            @__ctrl.Visible = false;
            @__ctrl.Text = "Reviewed And Approved";
            @__ctrl.OnClientClick = "return Save_Click();";
            @__ctrl.CssClass = "btnApprove";
            @__ctrl.Click -= new System.EventHandler(this.btnDOSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnDOSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnUMDisapprive() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnUMDisapprive = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnUMDisapprive";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary");
            @__ctrl.Visible = false;
            @__ctrl.Text = "Disapprove";
            @__ctrl.CssClass = "btnReject";
            @__ctrl.Click -= new System.EventHandler(this.btnUMDisapprove_Click);
            @__ctrl.Click += new System.EventHandler(this.btnUMDisapprove_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnDMDisapprive() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnDMDisapprive = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnDMDisapprive";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary");
            @__ctrl.Visible = false;
            @__ctrl.Text = "Disapprove";
            @__ctrl.CssClass = "btnReject";
            @__ctrl.Click -= new System.EventHandler(this.btnDMDisapprove_Click);
            @__ctrl.Click += new System.EventHandler(this.btnDMDisapprove_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnDODisapprive() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnDODisapprive = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnDODisapprive";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-primary");
            @__ctrl.Visible = false;
            @__ctrl.Text = "Disapprove";
            @__ctrl.CssClass = "btnReject";
            @__ctrl.Click -= new System.EventHandler(this.btnDODisapprove_Click);
            @__ctrl.Click += new System.EventHandler(this.btnDODisapprove_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlwaiver_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.waiver_div = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "col-sm-12");
            @__ctrl.ID = "waiver_div";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    Safety Incident Recommendations Waiver (IR-7 )
                </div>
                <div class=""panel-body"">
                    <div class=""form-group"">
                        <div class=""row"">
                            <div class=""col-lg-6"">
                                <label>Safety incident report no<span style=""color: red"">&nbsp;*</span></label>
                                "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl1;
            @__ctrl1 = this.@__BuildControlSafetyIncidentReportNo_tf();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                 <label id=""SafetyIncidentReportNo_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                            <div class=""col-lg-6"">
                                <label>Recommendation no<span style=""color: red"">&nbsp;*</span></label>
                                "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl2;
            @__ctrl2 = this.@__BuildControlRecommendationNo_tf();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                 <label id=""RecommendationNo_msg"" hidden style=""color: red"">You can't leave this empty.</label>

                            </div>
                        </div>
                    </div>
                    <div class=""form-group"">
                        <div class=""row"">
                            <div class=""col-lg-6"">
                                <label>Unit/Area<span style=""color: red"">&nbsp;*</span></label>
                                <br />
                                "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl3;
            @__ctrl3 = this.@__BuildControlSection_ddl();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl4;
            @__ctrl4 = this.@__BuildControlSection_hdn();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl5;
            @__ctrl5 = this.@__BuildControlHidden1();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""Section_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                            <div class=""col-lg-6"">
                                <label>Department</label>
                                <br />
                                "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl6;
            @__ctrl6 = this.@__BuildControlDepartment_ddl();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            global::System.Web.UI.HtmlControls.HtmlInputHidden @__ctrl7;
            @__ctrl7 = this.@__BuildControlDepartment_hdn();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""Department_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                        </div>
                    </div>
                    <div class=""form-group"">
                        <div class=""row"">
                            <div class=""col-lg-6"">
                                <label>Date<span style=""color: red"">&nbsp;*</span></label>

                                <div class=""form-group"">
                                    "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl8;
            @__ctrl8 = this.@__BuildControlDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                 <label id=""Date_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                               
                            </div>
                            <div class=""col-lg-6"">
                                <label>Recommendation completion due date<span style=""color: red"">&nbsp;*</span></label>

                                <div class=""form-group"">
                                    "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl9;
            @__ctrl9 = this.@__BuildControlRecommendationCompletionDueDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                 <label id=""RecommendationCompletionDueDate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                </div>
                               
                            </div>
                        </div>
                    </div>
                    <div class=""form-group"">
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                <label>Description of the recommendations<span style=""color: red"">&nbsp;*</span></label>

                                "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl10;
            @__ctrl10 = this.@__BuildControlDescriptionOfTheRecommendations_ta();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""DescriptionOfTheRecommendations_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>

                            <div class=""col-lg-12"">
                                <label>Recommendation reason<span style=""color: red"">&nbsp;*</span></label>

                                "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl11;
            @__ctrl11 = this.@__BuildControlRecommendationReason_ta();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                 <label id=""RecommendationReason_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                            </div>
                        </div>
                    </div>
                    <div class=""form-group"">
                        <div class=""row"">
                            <div class=""col-lg-6"">
                                <label>New Target Date<span style=""color: red"">&nbsp;*</span></label>

                                <div class=""form-group"">
                                    "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl12;
            @__ctrl12 = this.@__BuildControlNewTargetDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                <label id=""NewTargetDate_msg"" hidden style=""color: red"">You can't leave this empty.</label>
                                <label id=""NewTargetDateCompare_msg"" hidden style=""color: red"">NewTarget date must be greater than Recommendation Completion Due Date.</label>
                                </div>
                                
                            </div>
                            <div class=""col-lg-6"">
                            </div>
                        </div>
                    </div>
                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl13;
            @__ctrl13 = this.@__BuildControlInitiator_div();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl14;
            @__ctrl14 = this.@__BuildControlUM_div();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl15;
            @__ctrl15 = this.@__BuildControlDM_div();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl16;
            @__ctrl16 = this.@__BuildControlDO_div();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n\r\n\r\n                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl17;
            @__ctrl17 = this.@__BuildControlhdnID();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl18;
            @__ctrl18 = this.@__BuildControlhdnRecommendationListName();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl19;
            @__ctrl19 = this.@__BuildControlhdnParentList();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl20;
            @__ctrl20 = this.@__BuildControlhdnFRID();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl21;
            @__ctrl21 = this.@__BuildControlhdnLink();
            @__parser.AddParsedSubObject(@__ctrl21);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl22;
            @__ctrl22 = this.@__BuildControlhdnTaskName();
            @__parser.AddParsedSubObject(@__ctrl22);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                <div class=\"form-group pull-right\">\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl23;
            @__ctrl23 = this.@__BuildControlbtnSaveAsDraft();
            @__parser.AddParsedSubObject(@__ctrl23);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl24;
            @__ctrl24 = this.@__BuildControlbtnSave();
            @__parser.AddParsedSubObject(@__ctrl24);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl25;
            @__ctrl25 = this.@__BuildControlbtnCancel();
            @__parser.AddParsedSubObject(@__ctrl25);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl26;
            @__ctrl26 = this.@__BuildControlbtnUMSave();
            @__parser.AddParsedSubObject(@__ctrl26);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl27;
            @__ctrl27 = this.@__BuildControlbtnDMSave();
            @__parser.AddParsedSubObject(@__ctrl27);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl28;
            @__ctrl28 = this.@__BuildControlbtnDOSave();
            @__parser.AddParsedSubObject(@__ctrl28);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl29;
            @__ctrl29 = this.@__BuildControlbtnUMDisapprive();
            @__parser.AddParsedSubObject(@__ctrl29);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl30;
            @__ctrl30 = this.@__BuildControlbtnDMDisapprive();
            @__parser.AddParsedSubObject(@__ctrl30);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl31;
            @__ctrl31 = this.@__BuildControlbtnDODisapprive();
            @__parser.AddParsedSubObject(@__ctrl31);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n            </div>\r\n        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlwaiverNotAvailable_lb() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("label");
            this.waiverNotAvailable_lb = @__ctrl;
            @__ctrl.ID = "waiverNotAvailable_lb";
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SL.FG.FFL.WebParts.WaiverForm.WaiverForm @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<link href=\"/_layouts/15/SL.FG.FFL/CSS/FGStyle.css\" rel=\"stylesheet\" />\r\n\r\n" +
                        "<div class=\"container\">\r\n    <div class=\"row\">\r\n        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlwaiver_div();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <div class=\"col-sm-12\" id=\"notWaiver_div\" style=\"display: none\">\r\n     " +
                        "       <span style=\"color: red\">\r\n                "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl2;
            @__ctrl2 = this.@__BuildControlwaiverNotAvailable_lb();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </span>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n\r\n\r\n<script src=\"/_l" +
                        "ayouts/15/SL.FG.FFL/Scripts/jQuery.js\"></script>\r\n<script src=\"/_layouts/15/SL.F" +
                        "G.FFL/Scripts/Validation/Waiver.js\"></script>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
